### PR TITLE
Parser Errors

### LINKED ISSUE #246: Improve Misleading Parse Errors
```
Expected token '}' at line 10, column 3:
  func foo() -> Address {
  ^^^^
Failed to compile.
```

If there is a malformed expression in the parser it currently outputs an unhelpful error of expecting a closing token. 

This is because the code attempts all possible options for its body and all the errors are hidden from the user.

### PR DESCRIPTION
**Pull request by DJRHails**
Fixes #246 

# Implementation Overview
Currently there are no errors emitted from the Parser, this PR fixes that.

Still needs to check that all errors are being used and write test cases for all of the above
# Checklist

- [x] Remove all TODOs, debug prints, whitespace changes
- [x] Update docs/grammar.abnf if necessary
- [ ] Include tests
- [x] Add `review wanted` label, remove "WIP" in PR title

### CODE REVIEW

File: Sources/Diagnostic/DiagnosticsFormatter.swift [hunk 1]
```diff
@@ -41,7 +41,7 @@ public struct DiagnosticsFormatter {
     let infoLine = "\(infoTopic)\(sourceFileText):"
     let body: String
 
-    if let compilationContext = compilationContext, let file = diagnosticFile {
+    if let compilationContext = sourceContext, let file = diagnosticFile {
```
Comment (bearbin) [inline Sources/Diagnostic/DiagnosticsFormatter.swift]: This could be changed to `sourcecontext` as well.

**Comment by DJRHails** [comment]
I recommend merging this before expected-error tests are added (and we'll create a separate PR for that) as this is a blocking commit due to Parser rewrite. The current test suite already checks the Parser works as effectively as the previous one, but the messages aren't checked yet.

File: Sources/Parser/Parser+Expressions.swift [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+      guard let index = indexOfFirstAtCurrentDepth([.punctuation(op)], maxIndex: limitTokenIndex) else { continue }
+      let lhs = try parseExpression(upTo: index)
+      let operatorToken = try consume(.punctuation(op), or: .expectedValidOperator(at: latestSource))
+      let rhs = try parseExpression(upTo: limitTokenIndex)
+      return BinaryExpression(lhs: lhs, op: operatorToken, rhs: rhs)
+    }
+    return nil
+  }
+
+  // MARK: Bracked
```
Comment (bearbin) [inline Sources/Parser/Parser+Expressions.swift]: Bracked?
