### PR TITLE
Make sourceLocation indicators work with tabs not just spaces.

### LINKED ISSUE #313: SourceLocation does not work with tabs for indentation
The highlighted sections are misaligned. Solution is to pre-process and replace tabs by spaces.

### PR DESCRIPTION
**Pull request by bearbin**
Fixes #313 

# Implementation Overview

Replace tabs with single spaces before printing lines.

# Notes

Not really an optimal solution. Best would be to copy the indentation from the source line to the indicator line, then pad, but I couldn't find an easy way to do that so this also works.

# Checklist

- [x] Remove all TODOs, debug prints, whitespace changes
- [x] Update docs/grammar.abnf if necessary
- [x] Include tests (N/A)
- [x] Add `review wanted` label, remove "WIP" in PR title

### CODE REVIEW

File: Sources/Diagnostic/DiagnosticsFormatter.swift [hunk 1]
```diff
@@ -68,13 +68,15 @@ public struct DiagnosticsFormatter {
     let sourceLines = sourceCode.components(separatedBy: "\n")
     guard let sourceLocation = sourceLocation else { return "" }
 
-    let spaceOffset = sourceLocation.column != 0 ? sourceLocation.column - 1 : 0
+    let sourceLine = sourceLines[sourceLocation.line - 1].replacingOccurrences(of: "\t", with: " ")
```
Comment (DJRHails) [inline Sources/Diagnostic/DiagnosticsFormatter.swift]: Should this be double spaced?

Comment (bearbin) [reply Sources/Diagnostic/DiagnosticsFormatter.swift]: I'm only replacing tabs with single spaces as I couldn't think of an easy way to count the number of tabs as they are replaced so additional spaces can be added to the indicator.

Comment (SusanEisenbach) [reply Sources/Diagnostic/DiagnosticsFormatter.swift]: Ideally this should be rewritten so it finds where the diagnostic message should start on the line rather than indenting one space for each tab in the original diagnostic.
