### PR TITLE
Emit error when failed to conform to trait

### LINKED ISSUE #366: Failure to fully implement trait
This is a subtask of #365

### LINKED ISSUE #367: Trait almost implemented with incorrect names / types / restrictions
This is a subtask of #365

### PR DESCRIPTION
**Pull request by DJRHails**
Fixes #367 
Fixes #366 

# Implementation Overview

# Notes

# Checklist

- [x] Remove all TODOs, debug prints, whitespace changes
- [x] Add `review wanted` label, remove "WIP" in PR title

### CODE REVIEW

File: Sources/AST/Declaration/FunctionSignatureDeclaration.swift [hunk 1]
```diff
@@ -42,6 +42,17 @@ public struct FunctionSignatureDeclaration: ASTNode {
...
+  // MARK: - Equatable
+  public static func == (lhs: FunctionSignatureDeclaration, rhs: FunctionSignatureDeclaration) -> Bool {
+    return lhs.identifier.name == rhs.identifier.name &&
+      lhs.modifiers.map{ $0.kind } == rhs.modifiers.map{ $0.kind } &&
+      lhs.attributes.map{ $0.kind } == rhs.attributes.map{ $0.kind } &&
+      lhs.resultType?.rawType == rhs.resultType?.rawType &&
+      lhs.parameters.map({ $0.identifier.name }) == rhs.parameters.map({ $0.identifier.name }) &&
+      lhs.parameters.map({ $0.type.rawType }) == rhs.parameters.map({ $0.type.rawType }) &&
+      lhs.parameters.map({ $0.isInout }) == rhs.parameters.map({ $0.isInout })
+  }
```
Comment (bearbin) [inline Sources/AST/Declaration/FunctionSignatureDeclaration.swift]: There are parentheses on some of these maps but not others. They should all be consistent.
